name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the live branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ job.status }}
    steps:
      - name: Succeed
        # Fail on purpose to test notify-failure
        run: |
          exit 1 
    #uses: ./.github/workflows/test-frontend.yml
    
  run-backend-tests:
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ job.status }}
    steps:
      - name: Succeed
        # Succeed on purpose to test notify-failure
        run: |
          exit 0
    #uses: ./.github/workflows/test-back.yml

  deploy:
    needs: [run-frontend-tests, run-backend-tests]
    outputs:
      job-status: ${{ job.status }}
    if: ${{ success() }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:    
      - name: log into VPS and trigger deploy script
        uses: appleboy/ssh-action@master
        if: ${{ success() }}
        with:
          host: ${{ secrets.SSH_HOST }} # uses secrets stored in the Secrets tab
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: sh ~/devops-CI-S8-GRP1/App/deploy.sh
          
  notify-success:
    needs: [run-frontend-tests, run-backend-tests, deploy]
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: notify success on discord
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Action successful"
          
  notify-failure:
    needs: [run-frontend-tests, run-backend-tests, deploy]
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
      - name: notify failure on discord
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "❌ Deployment failed ❌"
          embed-color: 15158332
          embed-description: |
            Job statuses :
            - Frontend tests: ${{ needs.run-frontend-tests.outputs.job-status == 'success' && '✅' || '❌'}}
            - Backend tests: ${{ needs.run-backend-tests.outputs.job-status == 'success' && '✅' || '❌' }}
            - Deploy tests: ${{ needs.deploy.outputs.job-status == 'success' && '✅' || '❌' }}
            
          
