name: Test backend

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/Backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'App/Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Test
       run: docker-compose -f App/Backend/docker-compose.test.yml up 
