name: Test backend

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/Backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'App/Backend/**'
  workflow_call:
    outputs:
      job-status: 
        value: ${{ jobs.test.outputs.job-status }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ job.status }}
    steps:
     - uses: actions/checkout@v2
     - name: Test
       run: docker-compose -f App/Backend/docker-compose.test.yml up --abort-on-container-exit
