name: Test Frontend

on:
  push:
    branches: [ "master" ]
    paths:
      - 'App/Frontend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'App/Frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Test
       run: docker-compose -f App/Front/docker-compose.test.yml up --abort-on-container-exit
